# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Supabase credentials — set your own values here
SUPABASE_URL=https://excvhccfmizmfctpmehf.supabase.co
SUPABASE_KEY=sb_publishable_ThKnl8r7_p-CdHJQoGOFUg_nJH5zZ0f
